language: node_js
node_js: 
  - "node"
services:
  - postgresql
cache:
  directories:
    - node_modules
before_script:
- npm install -g gulp-cli
- psql -c 'create database test_db;' -U postgres
- NODE_ENV=test sequelize db:migrate
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js